server:
  port: 30001
spring:
  application:
    name: auth-service
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}
