server:
  port: 10000
spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: dyzp.work
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: dyzp.work
        instance-id: ${spring.application.name}

    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins:
              - "http://localhost:8013"
              - "http://dyzp.work"
              - "http://dyzp.work:9999"
            allowed-headers: "*"
            allowedMethods: "*"

      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: show-love
          uri: lb://show-love
          predicates:
            - Path=/love/**

